development:
  adapter: postgresql
  encoding: unicode
  database: sinatra_dev
  pool: 2
  username: postgres
  password: Coding123

production:
  adapter: postgresql
  encoding: unicode
  database: sinatra_production
  pool: 2
  username:
  password:
